apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-delivery-frontend-service
  template:
    metadata:
      labels:
        app: food-delivery-frontend-service
    spec:
      containers:
      - name: frontend-container
        image: us-central1-docker.pkg.dev/ha-demo-480714/my-docker-repo/food-delivery-frontend:latest
        ports:
        - containerPort: 80
      
      # NEW: Monitoring Sidecar
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - -nginx.scrape-uri=http://localhost:80/nginx_status
        ports:
        - containerPort: 9113

---
# NEW: Tell GCP to collect these metrics
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: frontend-monitoring
spec:
  selector:
    matchLabels:
      app: food-delivery-frontend-service
  endpoints:
  - port: 9113
    interval: 30s
