ce# Kubernetes API version for Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # Name of the Deployment
  name: food-delivery-frontend-deployment
  # Labels for easy identification/selection
  labels:
    app: food-delivery-frontend
spec:
  # Number of desired replicas (pods)
  replicas: 3
  # Selector to identify which Pods belong to this Deployment
  selector:
    matchLabels:
      app: food-delivery-frontend-service
  template:
    metadata:
      labels:
        app: food-delivery-frontend-service
    spec:
      containers:
      - name: frontend-container
        # UPDATED: Pointing to your Google Artifact Registry
        # Cloud Build will automatically replace this with the specific $SHORT_SHA tag
        image: us-central1-docker.pkg.dev/ha-demo-480714/my-docker-repo/frontend
        imagePullPolicy: Always
        ports:
        # Container port must match the EXPOSE port in your Dockerfile (80)
        - containerPort: 80
        resources:
          # Define resource requests and limits for better scheduling and stability
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
