apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-frontend-deployment
  labels:
    app: food-delivery-frontend-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-delivery-frontend-service
  template:
    metadata:
      labels:
        app: food-delivery-frontend-service
    spec:
      containers:
      - name: frontend-container
        image: us-central1-docker.pkg.dev/ha-demo-480714/my-docker-repo/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
