apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-delivery-backend
  template:
    metadata:
      labels:
        app: food-delivery-backend
    spec:
      containers:
      - name: food-delivery-backend
        image: duskyguy/food-delivery-backend:latest
        ports:
        - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: food-delivery-backend-service
spec:
  type: NodePort
  selector:
    app: food-delivery-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002  # Fixed port so you can always find it
