apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-delivery-backend
  template:
    metadata:
      labels:
        app: food-delivery-backend
    spec:
      containers:
      - name: food-delivery-backend
        # Updated to point to your GCP Artifact Registry
        image: us-central1-docker.pkg.dev/ha-demo-480714/my-app-repo/food-delivery-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          # If password is 'Taylor@', use 'Taylor%40'
          value: "mongodb+srv://shyam:Taylor%40@cluster0.xyz.mongodb.net/food-del"

---
apiVersion: v1
kind: Service
metadata:
  name: food-delivery-backend-service
spec:
  # Changed to LoadBalancer so you get a public IP for your Frontend to connect to
  type: LoadBalancer
  selector:
    app: food-delivery-backend
  ports:
    - port: 5000
      targetPort: 5000
